loss_gamma1: 0.8
loss_gamma2: 0.2
num_epochs: 30
adam_lr: 0.001
#step_lr_step_size: 30
#step_lr_gamma: 0.1
calc_eval_loss_interval: 100
batch_size: 4
train_ratio: 0.8
print_loss_interval: 100
early_stopping_patience: 5
checkpoint_path: "/home/student/Documents/mds12/sho/final_year_project/Data/output/uft/run_2024_05_13_23_04_21/denoiser.pth"
images_dir: "/home/student/Documents/mds12/sho/final_year_project/Data/paired"
save_dir: "/home/student/Documents/mds12/sho/final_year_project/Data/output/uft_sft"