denoiser_adam_lr: 4.776729571225422e-05
discriminator_adam_lr: 0.009627422411867004
denoiser_adversarial_loss_clip_max: 0.7253553053728639
denoiser_adversarial_loss_clip_min: 0.42959290591546195
num_epochs: 11
step_lr_step_size: 30
step_lr_gamma: 0.1
batch_size: 4
print_loss_interval: 107
calc_eval_loss_interval: 200
denoiser_loss_b1: 0.654205478362656
denoiser_loss_b2: 0.34579452163
early_stopping_patience: 5
checkpoint_path: "/home/student/Documents/mds12/sho/final_year_project/src/toenet/checkpoint/checkpoint.pth.tar"
images_dir: "/home/student/Documents/mds12/sho/final_year_project/Data/unpaired"
save_dir: "/home/student/Documents/mds12/sho/final_year_project/Data/output/uft"
eval_dir: "/home/student/Documents/mds12/sho/final_year_project/Data/paired"
