denoiser_adam_lr: 4.776729571225422e-05
discriminator_adam_lr: 0.004821538386409875
denoiser_adversarial_loss_clip_max: 0.4337323515489777
denoiser_adversarial_loss_clip_min: 0.3332490914063566
num_epochs: 13
step_lr_step_size: 30
step_lr_gamma: 0.1
batch_size: 8
print_loss_interval: 107
calc_eval_loss_interval: 409
denoiser_loss_b1: 0.1562460608300291
denoiser_loss_b2: 0.84375393917
early_stopping_patience: 5
checkpoint_path: "/home/student/Documents/mds12/sho/final_year_project/src/toenet/checkpoint/checkpoint.pth.tar"
images_dir: "/home/student/Documents/mds12/sho/final_year_project/Data/unpaired"
save_dir: "/home/student/Documents/mds12/sho/final_year_project/Data/output/uft"
eval_dir: "/home/student/Documents/mds12/sho/final_year_project/Data/paired"
